# Generated by Django 5.2.6 on 2025-09-22 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='alternateMobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('mobileNo', models.IntegerField(blank=True, max_length=100, null=True)),
                ('feedbackCategory', models.IntegerField(blank=True, default=1, null=True)),
                ('feedbackText', models.TextField(blank=True, null=True)),
                ('feedbackPhotoURL', models.CharField(blank=True, max_length=400, null=True)),
                ('feedbackDateTime', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('areaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_Area', to='admin_pannel.areas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_modified_by', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_PaymentUserid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblFeedbacks',
            },
        ),
        migrations.CreateModel(
            name='SMSMaster',
            fields=[
                ('templateId', models.AutoField(primary_key=True, serialize=False)),
                ('templateTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('templateMessageBody', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblSMSMaster',
            },
        ),
        migrations.CreateModel(
            name='SMSTransaction',
            fields=[
                ('smsTransId', models.AutoField(primary_key=True, serialize=False)),
                ('smsBody', models.TextField(blank=True, null=True)),
                ('smsTo', models.CharField(blank=True, max_length=10, null=True)),
                ('smsFrom', models.CharField(blank=True, max_length=10, null=True)),
                ('smsCategory', models.IntegerField(blank=True, null=True)),
                ('smsStatus', models.IntegerField(blank=True, null=True)),
                ('smsSendOn', models.IntegerField(blank=True, null=True)),
                ('smsDeliveredOn', models.IntegerField(blank=True, null=True)),
                ('smsMethod', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_modified_by', to=settings.AUTH_USER_MODEL)),
                ('registrationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_registrationId', to='admin_pannel.registrations')),
                ('smsRequestByUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_smsRequestByUserId', to=settings.AUTH_USER_MODEL)),
                ('smsTemplateId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_smsTemplateId', to='admin_pannel.smsmaster')),
            ],
            options={
                'db_table': 'tblSMSTransactions',
            },
        ),
        migrations.CreateModel(
            name='TourExpenses',
            fields=[
                ('expenseId', models.AutoField(primary_key=True, serialize=False)),
                ('expenseDateTime', models.DateTimeField(blank=True, null=True)),
                ('expenseTime', models.TimeField(blank=True, null=True)),
                ('expenseAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expenseRemark', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('expenseUserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_expenseUserId', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'TourExpenses',
            },
        ),
    ]
