# Generated by Django 5.2.6 on 2025-09-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0002_alter_registrations_alternatemobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mobileNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='aadharNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
