# Generated by Django 5.2.6 on 2025-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0003_alter_feedback_mobileno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='gender',
        ),
        migrations.AlterField(
            model_name='registrations',
            name='aadharNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='alternateMobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
