# Generated by Django 5.2.6 on 2025-09-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0004_remove_registrations_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='gender',
            field=models.IntegerField(blank=True, db_comment='1 = Female, 2 = Male', default=1, null=True),
        ),
    ]
