# Generated by Django 5.0.1 on 2025-10-01 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0005_registrations_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatrabuses',
            name='busName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yatrabuses_busName', to='admin_pannel.busnames'),
        ),
    ]
