# Generated by Django 5.2.7 on 2025-10-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0006_alter_yatrabuses_busname'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='BookingMobileNo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
