# Generated by Django 5.2.7 on 2025-10-16 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0007_registrations_bookingmobileno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='age',
            field=models.SmallIntegerField(db_column='Age', default=0),
        ),
        migrations.AddField(
            model_name='registrations',
            name='parent_id',
            field=models.IntegerField(blank=True, db_column='ParentId', default=0, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='ration_card_no',
            field=models.CharField(blank=True, db_column='RationCardNo', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='registrations',
            name='ration_card_photo',
            field=models.CharField(blank=True, db_column='RationCardPhoto', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smstransaction',
            name='smsResponse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DiwaliKirana',
            fields=[
                ('DiwaliKiranaId', models.AutoField(primary_key=True, serialize=False)),
                ('DiwaliYearMonth', models.CharField(default='2025-10', max_length=7)),
                ('TokenNo', models.IntegerField(unique=True)),
                ('TokenQR', models.CharField(max_length=8)),
                ('TokenURL', models.CharField(blank=True, max_length=255, null=True)),
                ('RationCardNo', models.CharField(max_length=25)),
                ('TokenStatus', models.SmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('RegistrationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiwaliKirana_RegistrationId', to='admin_pannel.registrations')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblDiwaliKirana',
            },
        ),
    ]
