# Generated by Django 5.2.7 on 2025-10-31 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0009_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='age',
            field=models.SmallIntegerField(blank=True, db_column='Age', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='areaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_Area', to='admin_pannel.areas'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='bloodGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_BloodGroup', to='admin_pannel.bloodgroup'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_UserId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('EventRegistrationId', models.AutoField(primary_key=True, serialize=False)),
                ('RegistrationDateTime', models.DateTimeField(auto_now_add=True)),
                ('RegistrationStatus', models.SmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('EventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventRegistrations_EventId', to='admin_pannel.event')),
                ('RegistrationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventRegistrations_RegistrationId', to='admin_pannel.registrations')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventRegistration',
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('display_label', models.CharField(help_text='Custom label for the form field', max_length=255)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which fields appear on the form')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fields', to='admin_pannel.event')),
            ],
            options={
                'db_table': 'EventRegistrationField',
            },
        ),
    ]
