# Generated by Django 5.2.7 on 2025-10-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0010_alter_registrations_age_alter_registrations_areaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='dateOfRegistration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
