# Generated by Django 5.2.7 on 2025-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0011_alter_registrations_dateofregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
