# Generated by Django 5.2.7 on 2025-10-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0012_alter_registrations_last_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
