# Generated by Django 5.2.7 on 2025-11-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0013_alter_registrations_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='QRCode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='QRURL',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='TokenNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
