# Generated by Django 5.2.7 on 2025-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0014_eventregistration_qrcode_eventregistration_qrurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='VoterID_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
