# Generated by Django 5.2.7 on 2025-11-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0016_eventregistration_reg_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(blank=True, choices=[('normal', 'Normal Event'), ('distribution', 'Distribution Event')], default='normal', max_length=20, null=True),
        ),
    ]
