# Generated by Django 5.2.7 on 2026-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0017_alter_event_eventtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
