# Generated by Django 5.2.7 on 2026-01-28 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0019_alter_areas_created_by_alter_areas_deleted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='BookingMobileNo',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='VoterID_No',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='ration_card_no',
        ),
        migrations.RemoveField(
            model_name='registrations',
            name='zonePreference',
        ),
        migrations.AddField(
            model_name='ticketsnew',
            name='booking_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ticketsnew',
            name='zone_preference',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='yatrastatus',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='yatrastatus',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='ElectionManagement',
            fields=[
                ('ElectionId', models.AutoField(primary_key=True, serialize=False)),
                ('VotingCardNo', models.CharField(blank=True, max_length=25, null=True)),
                ('BoothAddress', models.TextField(blank=True, null=True)),
                ('AssemblyNo', models.CharField(blank=True, max_length=50, null=True)),
                ('YadiNo', models.CharField(blank=True, max_length=50, null=True)),
                ('SrNo', models.IntegerField(blank=True, null=True)),
                ('CallStatus', models.IntegerField(blank=True, db_comment='0=Pending, 1=Success, 2=Failed/Unreachable', default=0, null=True)),
                ('VotingStatus', models.IntegerField(blank=True, db_comment='0=Not Voted, 1=Voted', default=0, null=True)),
                ('CallerName', models.CharField(blank=True, max_length=150, null=True)),
                ('CallTimestamp', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('CallerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_CallerId', to=settings.AUTH_USER_MODEL)),
                ('RegistrationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Election_RegistrationId', to='admin_pannel.registrations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblElectionManagement',
            },
        ),
    ]
