# Generated by Django 5.2.7 on 2026-01-28 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0020_remove_registrations_bookingmobileno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserFirstname', models.CharField(max_length=100)),
                ('UserLastname', models.CharField(blank=True, max_length=100, null=True)),
                ('UserMobileNo', models.CharField(max_length=15, unique=True)),
                ('UserLoginPin', models.IntegerField()),
                ('UserStatus', models.IntegerField(default=1)),
                ('UserRole', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Users_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblUsers',
            },
        ),
    ]
