# Generated by Django 5.2.7 on 2026-01-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0021_tblusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsnew',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ticketsnew',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TicketsNew_Userid', to='admin_pannel.tblusers'),
        ),
    ]
