# Generated by Django 5.2.8 on 2026-01-28 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0022_remove_ticketsnew_user_id_ticketsnew_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsnew',
            old_name='UserId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='tblusers',
            name='last_modified_on',
        ),
        migrations.AlterField(
            model_name='areas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Area_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Area_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='areas',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Area_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BloodGroup_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BloodGroup_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BloodGroup_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busnames',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusNames_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busnames',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusNames_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busnames',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusNames_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busseats',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusSeats_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busseats',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusSeats_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='busseats',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BusSeats_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='diwalikirana',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='diwalikirana',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='diwalikirana',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DiwaliKirana_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='electionmanagement',
            name='CallerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_CallerId', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='electionmanagement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='electionmanagement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='electionmanagement',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Election_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Event_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='EventRegistration_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Feedback_PaymentUserid', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gender_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gender_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Gender_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='paymentUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Payment_PaymentUserid', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Registrations_UserId', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smsmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smsmaster',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smsmaster',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSMaster_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smstransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smstransaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smstransaction',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='smstransaction',
            name='smsRequestByUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SMSTransaction_smsRequestByUserId', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='tblusers',
            name='UserFirstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsnew',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TicketsNew_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='ticketsnew',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TicketsNew_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='ticketsnew',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TicketsNew_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='tourexpenses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='tourexpenses',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='tourexpenses',
            name='expenseUserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_expenseUserId', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='tourexpenses',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TourExpenses_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrabuses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraBus_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrabuses',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraBus_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrabuses',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraBus_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatraroutes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraRoute_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatraroutes',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraRoute_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatraroutes',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraRoute_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatras',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yatras_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatras',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yatras_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatras',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Yatras_modified_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrastatus',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraStatus_created_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrastatus',
            name='deleted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraStatus_deleted_by', to='admin_pannel.tblusers'),
        ),
        migrations.AlterField(
            model_name='yatrastatus',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='YatraStatus_modified_by', to='admin_pannel.tblusers'),
        ),
    ]
