# Generated by Django 5.2.8 on 2026-02-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0023_rename_userid_ticketsnew_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BJPOffice',
            fields=[
                ('bjp_office_id', models.AutoField(primary_key=True, serialize=False)),
                ('voter_name', models.CharField(blank=True, max_length=150, null=True)),
                ('voter_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('record_type', models.CharField(choices=[('MissingInfoCollect', 'Missing Info Collect'), ('ComplaintRegistration', 'Complaint Registration')], default='ComplaintRegistration', max_length=30)),
                ('complaint_category', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_type', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Emergency', 'Emergency')], default='Normal', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('InProgress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Open', max_length=30)),
                ('handled_by_id', models.IntegerField(blank=True, null=True)),
                ('handled_by_name', models.CharField(blank=True, max_length=120, null=True)),
                ('area_text', models.CharField(blank=True, max_length=120, null=True)),
                ('address_text', models.TextField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('missing_info_notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BJOOffice_created_by', to='admin_pannel.tblusers')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BJOOffice_deleted_by', to='admin_pannel.tblusers')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BJOOffice_modified_by', to='admin_pannel.tblusers')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bjp_office_records', to='admin_pannel.registrations')),
            ],
            options={
                'db_table': 'BJPOffice',
            },
        ),
    ]
