# Generated by Django 5.2.8 on 2026-02-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0024_bjpoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/complaints/'),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/complaints/'),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/complaints/'),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='doc_aadhar_img',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/aadhar/'),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='doc_ration_img',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/ration/'),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='doc_voting_img',
            field=models.ImageField(blank=True, null=True, upload_to='office_docs/voting/'),
        ),
    ]
