# Generated by Django 5.2.8 on 2026-02-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0025_bjpoffice_complaint_img_1_bjpoffice_complaint_img_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bjpoffice',
            name='complaint_img_1',
        ),
        migrations.RemoveField(
            model_name='bjpoffice',
            name='complaint_img_2',
        ),
        migrations.RemoveField(
            model_name='bjpoffice',
            name='complaint_img_3',
        ),
        migrations.RemoveField(
            model_name='bjpoffice',
            name='doc_aadhar_img',
        ),
        migrations.RemoveField(
            model_name='bjpoffice',
            name='doc_ration_img',
        ),
        migrations.RemoveField(
            model_name='bjpoffice',
            name='doc_voting_img',
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_photo1_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_photo2_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='complaint_photo3_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='personal_aadhar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='personal_ration_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bjpoffice',
            name='personal_voting_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
