# Generated by Django 5.2.8 on 2026-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0026_remove_bjpoffice_complaint_img_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblusers',
            name='password_updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
