# Generated by Django 5.2.8 on 2026-02-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0027_tblusers_password_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bjpoffice',
            name='record_type',
            field=models.CharField(choices=[('MissingInfoCollect', 'Missing Info Collect'), ('ComplaintRegistration', 'Complaint Registration'), ('MASTER', 'MASTER')], default='ComplaintRegistration', max_length=30),
        ),
    ]
