# Generated by Django 5.2.8 on 2026-02-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0028_alter_bjpoffice_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='is_excel_updated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
