# Generated by Django 5.2.8 on 2026-06-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0030_counselorcalendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselorcalendar',
            old_name='endDateTime',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='counselorcalendar',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='counselorcalendar',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
