# Generated by Django 5.2.8 on 2026-06-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0031_rename_enddatetime_counselorcalendar_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselorcalendar',
            old_name='calendarId',
            new_name='calendar_id',
        ),
        migrations.RemoveField(
            model_name='counselorcalendar',
            name='googleMapsLink',
        ),
        migrations.RemoveField(
            model_name='counselorcalendar',
            name='locationName',
        ),
        migrations.AddField(
            model_name='counselorcalendar',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='counselorcalendar',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
