# Generated by Django 5.2.8 on 2026-09-22 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_pannel', '0032_rename_calendarid_counselorcalendar_calendar_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUserRights',
            fields=[
                ('right_id', models.AutoField(primary_key=True, serialize=False)),
                ('permissions', models.TextField(default='[]')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userright_created_by', to='admin_pannel.tblusers')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userright_deleted_by', to='admin_pannel.tblusers')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userright_modified_by', to='admin_pannel.tblusers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_rights', to='admin_pannel.tblusers')),
            ],
            options={
                'db_table': 'tblUserRights',
            },
        ),
    ]
